services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mydb
    ports:
      - "5432:5432" # Parte derecha puerto original postgres, izquierda es el que tú pones en tu máquina
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - monitoring-net

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres_exporter
    environment:
      DATA_SOURCE_NAME: "user=admin password=admin123 host=postgres port=5432 dbname=mydb sslmode=disable"
    depends_on:
      - postgres
    ports:
      - "9187:9187"
    networks:
      - monitoring-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus/data:/prometheus 
    ports:
      - "9090:9090"
    networks:
      - monitoring-net
    depends_on:
      - postgres_exporter

  grafana:
    image: grafana/grafana:latest
    logging:
      driver: "none"  # Esto muteará todos los logs de este contenedor
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    depends_on:
      - prometheus
    networks:
      - monitoring-net
    volumes:
      - ./data/grafana:/var/lib/grafana

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - monitoring-net
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin

networks:
  monitoring-net:
    driver: bridge
